# Puerto por defecto de Quarkus
quarkus.http.port=8080

# Habilitar CORS para que Laravel (u otro origen) pueda consumir la API
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/

# Nivel de log para ver la actividad en consola
quarkus.log.level=INFO
quarkus.log.console.enable=true
